services:
  redis:
    image: ${REDIS_IMAGE}
    restart: unless-stopped
    networks:
      - calendar-oauth2-network

  oauth2-proxy:
    image: ${OAUTH2_PROXY_IMAGE}
    restart: unless-stopped
    environment:
      - OAUTH2_PROXY_PROVIDER=${OAUTH2_PROXY_PROVIDER}
      - OAUTH2_PROXY_TENANT_ID=${OAUTH2_PROXY_TENANT_ID}
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_PROXY_REDIRECT_URL=${OAUTH2_PROXY_REDIRECT_URL}
      - OAUTH2_PROXY_UPSTREAMS=${OAUTH2_PROXY_UPSTREAMS}
      - OAUTH2_PROXY_EMAIL_DOMAINS=${OAUTH2_PROXY_EMAIL_DOMAINS}
      - OAUTH2_PROXY_HTTP_ADDRESS=${OAUTH2_PROXY_HTTP_ADDRESS}
      - OAUTH2_PROXY_OIDC_ISSUER_URL=${OAUTH2_PROXY_OIDC_ISSUER_URL}
      - OAUTH2_PROXY_COOKIE_SECURE=${OAUTH2_PROXY_COOKIE_SECURE}
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=${OAUTH2_PROXY_SKIP_PROVIDER_BUTTON}
      - OAUTH2_PROXY_REDIS_CONNECTION_URL=${OAUTH2_PROXY_REDIS_CONNECTION_URL}
      - OAUTH2_PROXY_SESSION_STORE_TYPE=${OAUTH2_PROXY_SESSION_STORE_TYPE}
    networks:
      - nginx-proxy-manager
      - calendar-oauth2-network
    expose:
      - "4180"
    depends_on:
      - redis
      - nginx-redirect

  nginx-redirect:
    image: ${NGINX_IMAGE}
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - calendar-oauth2-network
    expose:
      - "80"

networks:
  nginx-proxy-manager:
    external: true
  calendar-oauth2-network:
    driver: bridge
